# Generated by Django 5.1.7 on 2025-03-15 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ilia', max_length=250)),
                ('lastname', models.CharField(default='shubitidze', max_length=250)),
                ('age', models.IntegerField(default=28)),
                ('job', models.CharField(default='beck-end Developer', max_length=250)),
                ('date_of_birth', models.DateField(default=datetime.date(1996, 10, 30))),
            ],
        ),
    ]
