# Generated by Django 5.1.7 on 2025-03-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desctiption',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Soft Drinks', max_length=100),
        ),
    ]
