# Generated by Django 5.1.7 on 2025-03-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_orderitem_price_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
